name: sovits5
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - pytorch
  - pytorch-cuda
  - chardet
  - torchaudio
  - fsspec
  - pyworld
  - matplotlib
  - scikit-learn
  - scipy
  - tensorboard
  - faiss-cpu==1.7.4
  - transformers
  - tqdm
  - librosa
  - omegaconf
  #- gradio==3.36.1
  - gradio
  - ruamel.yaml
  - resampy
  - numpy==1.24
  - chardet


  - pip
  - pip:
    - soundfile
